theme: jekyll-theme-minimal
title: Christopher Kullenberg
description: Christopher Kullenberg personal homepage


navbar-links: 
    Facts:
            - CV: "https://github.com/christopherkullenberg/CV"
